import {
  removeAppStorage,
  getUserInfo,
  setUserInfo,
  getAdminUserInfo,
  setAdminUserInfo,
  getAutoLogin,
  setAutoLogin,
  getAdminAutoLogin,
  setAdminAutoLogin,
  getActiveLoading,
  activeLoading,
  inActiveLoading,
  checkEmail,
  checkPhoneNum,
  changeObjectArray,
  isMobile,
  OSInfo,
  isEmpty,
  isNotEmpty,
  getPageContentNum,
  removeNullValues,
  diffObjects,
  checkedProcess,
  checkedItemsProcess,
  downloadUrlFile,
  handleOnClickAllCheck,
  handleOnClickAllCheckItem,
  checkPassword,
  copyToClipboard,
  getAccessToken,
  setAccessToken,
  getRefreshToken,
  setRefreshToken,
  removeAccessToken,
  removeRefreshToken,
  getAdminAccessToken,
  setAdminAccessToken,
  getAdminRefreshToken,
  setAdminRefreshToken,
  removeAdminAccessToken,
  removeAdminRefreshToken,
  removeLocalItem,
  removeSessionItem,
  makeDaysOptionComp,
  getNumberStr,
  copyObject,
  changeObject,
  getBreakpoint,
  getFontSize,
  getHeight,
  setBridge,
  setFcmToken,
  getFcmToken,
} from './commonUtils';
import {
  execute,
  exLogin,
  exLogout,
  setMAutoLogin,
  getMAutoLogin,
  setSnsInfo,
  getSnsInfo,
  getInitPopFlag,
  setInitPopFlag,
  exGetFcmToken,
} from './executeUtils';
import {
  parseDateToStr,
  parseDateToArr,
  parseDateToYMD,
  parseTimeToTM,
  parseGetFlag,
  parseSetFlag,
  parseTextLine,
  parseLongText,
  parsePhoneNum,
  parseAmount,
  parseClipBoardForExcel,
  parseWeightValue,
  parseCeil,
  parseRemoveHyphen,
  getH,
} from './parseUtil';
import { handleConsonantsTitle } from './customUtils';

import { exportNum, exportRandomItem } from './exportUtil';

const utils = {
  setBridge,
  OSInfo,
  getBreakpoint,
  //
  setFcmToken,
  getFcmToken,
  parseRemoveHyphen,
  parseCeil,
  parseWeightValue,
  copyObject,
  changeObject,
  parseClipBoardForExcel,
  removeAppStorage,
  getUserInfo,
  setUserInfo,
  getAdminUserInfo,
  setAdminUserInfo,
  getAutoLogin,
  setAutoLogin,
  getAdminAutoLogin,
  setAdminAutoLogin,
  getActiveLoading,
  activeLoading,
  inActiveLoading,
  getNumberStr,
  makeDaysOptionComp,
  getAccessToken,
  setAccessToken,
  getRefreshToken,
  setRefreshToken,
  removeAccessToken,
  removeRefreshToken,
  getAdminAccessToken,
  setAdminAccessToken,
  getAdminRefreshToken,
  setAdminRefreshToken,
  removeAdminAccessToken,
  removeAdminRefreshToken,
  removeLocalItem,
  removeSessionItem,
  copyToClipboard,
  checkPassword,
  downloadUrlFile,
  diffObjects,
  checkPhoneNum,
  parseAmount,
  removeNullValues,
  checkEmail,
  parseTextLine,
  checkedProcess,
  changeObjectArray,
  isMobile,
  isEmpty,
  isNotEmpty,
  parseDateToStr,
  parseDateToArr,
  parseDateToYMD,
  parseTimeToTM,
  parseGetFlag,
  parseSetFlag,
  parseLongText,
  parsePhoneNum,
  getPageContentNum,
  handleOnClickAllCheck,
  handleOnClickAllCheckItem,
  checkedItemsProcess,
  getH,
  getFontSize,
  getHeight,

  // execute
  execute,
  exLogin,
  exLogout,
  setMAutoLogin,
  getMAutoLogin,
  setSnsInfo,
  getSnsInfo,
  getInitPopFlag,
  setInitPopFlag,
  exGetFcmToken,

  // export
  exportNum,
  exportRandomItem,

  // custom
  handleConsonantsTitle,
};

export default utils;
