import {
  removeAppStorage,
  getUserInfo,
  setUserInfo,
  getAutoLogin,
  setAutoLogin,
  getActiveLoading,
  activeLoading,
  inActiveLoading,
  checkEmail,
  checkPhoneNum,
  changeObjectArray,
  isMobile,
  isEmpty,
  isNotEmpty,
  getPageContentNum,
  removeNullValues,
  diffObjects,
  checkedProcess,
  checkedItemsProcess,
  downloadUrlFile,
  handleOnClickAllCheck,
  handleOnClickAllCheckItem,
  checkPassword,
  copyToClipboard,
  getAccessToken,
  setAccessToken,
  getRefreshToken,
  setRefreshToken,
  removeAccessToken,
  removeRefreshToken,
  removeLocalItem,
  removeSessionItem,
  makeDaysOptionComp,
  getNumberStr,
  copyObject,
  getBreakpoint,
} from './commonUtils';
import {
  parseDateToStr,
  parseDateToArr,
  parseDateToYMD,
  parseTimeToTM,
  parseGetFlag,
  parseSetFlag,
  parseTextLine,
  parseLongText,
  parsePhoneNum,
  parseAmount,
  parseClipBoardForExcel,
  parseWeightValue,
  parseCeil,
  parseRemoveHyphen,
} from './parseUtil';

import { getLALOInfo } from './customUtil';

import { exportNum } from './exportUtil';

const utils = {
  getBreakpoint,
  exportNum,
  parseRemoveHyphen,
  parseCeil,
  parseWeightValue,
  copyObject,
  parseClipBoardForExcel,
  removeAppStorage,
  getUserInfo,
  setUserInfo,
  getAutoLogin,
  setAutoLogin,
  getActiveLoading,
  activeLoading,
  inActiveLoading,
  getNumberStr,
  makeDaysOptionComp,
  getAccessToken,
  setAccessToken,
  getRefreshToken,
  setRefreshToken,
  removeAccessToken,
  removeRefreshToken,
  removeLocalItem,
  removeSessionItem,
  copyToClipboard,
  checkPassword,
  downloadUrlFile,
  diffObjects,
  checkPhoneNum,
  parseAmount,
  removeNullValues,
  checkEmail,
  parseTextLine,
  checkedProcess,
  changeObjectArray,
  isMobile,
  isEmpty,
  isNotEmpty,
  parseDateToStr,
  parseDateToArr,
  parseDateToYMD,
  parseTimeToTM,
  parseGetFlag,
  parseSetFlag,
  parseLongText,
  parsePhoneNum,
  getPageContentNum,
  handleOnClickAllCheck,
  handleOnClickAllCheckItem,
  checkedItemsProcess,
  //
  getLALOInfo,
};

export default utils;
